### ISSUE TITLE
problem installing nvm-setup for getpapers

### ISSUE THREAD

**Issue by kareenasingh** [petermr/openVirus#59]
share your screen and we can help you further.

**Comment by Pruthivrajan** [comment]
yes sure
![Screenshot (8)](https://user-images.githubusercontent.com/66299927/83551445-fb7f0500-a525-11ea-8f31-293791eeb3c1.png)

**Comment by kareenasingh** [comment]
what happens when you open the nvm-steup.exe ? can you run it once?

**Comment by Pruthivrajan** [comment]
![Screenshot (15)](https://user-images.githubusercontent.com/66299927/83551961-a68fbe80-a526-11ea-8bbb-1bffb09a38c1.png)
![Screenshot (14)](https://user-images.githubusercontent.com/66299927/83551962-a7c0eb80-a526-11ea-8372-e8b6c0d4be4a.png)
![Screenshot (13)](https://user-images.githubusercontent.com/66299927/83551964-a8598200-a526-11ea-8d0a-cb57516fb2f2.png)
![Screenshot (12)](https://user-images.githubusercontent.com/66299927/83551966-aa234580-a526-11ea-91df-29e95f67ec72.png)

**Comment by ziflex** [comment]
What error message are you getting?

**Comment by Pruthivrajan** [comment]
all done.  back to track

**Comment by petermr** [comment]
Thanks everyone,
A few points. 
* this may be viewed by anyone interested in the project, so a few words of introduction are needed.
* what is the problem?
* was it resolved? 
* what was it due to, and is any remedial action needed?
 
Was it:
* insufficient or incorrect documentation. If so , update the docs or raise an issue.
* an incorrect command. If so maybe there is a software solution to trap it.
* a platform problem.
* some other problem.

*This issue cannot be closed unless it is analysed and explained.*
